### PR TITLE
Added crc.xml converter.

### PR DESCRIPTION
**Pull request by AraHaan**
## Debug information

- Els_kom version: ``[your version here]``
- OS: ``[Your OS version here]``
- OS Arch: ``[Your OS Arch here]``
- OS Build: ``[Your OS Build here]``

### CODE REVIEW

**Comment by dc1284933037** [comment]
I get some problems when I build the Solution,I download Visual Studio 2017 and open the pcbuild.sln, I found the newest Visual Studio 2017 had no the WIN32 only X86,then I try to run and it remind me that cant found the file Els_kom_new-master\Els_kom\Resources\Els_kom.esc. I feel puzzled much

**Comment by AraHaan** [comment]
Well, I think the project will only build if it is a git clone.

**Comment by CatGirlsAreLife** [comment]
@dc1284933037 Look at #78 and see if it might help you. Sorry for the confusion.

**Comment by CatGirlsAreLife** [comment]
I think having the code to the packbuild project in Els_kom project when executed in command line with args might be a better option to eliminate that folder and project file. Let me test that though.

**Comment by CatGirlsAreLife** [comment]
I think each plugin should have a crc converter method that then this method would invoke doing the actual needed changes to the crc.xml file upon packing. This would releaviate the need of somehow overloading stuff manually on newer kom versions when needing to convert the crc.xml to the format it needs for that kom version making the weight go to the implementations using the IKomPlugin interface class.

**Pull request merged**
